name: Integration Test

on:
    workflow_dispatch:
        permissions:
        users:
            - ItayTheDar
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or any version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt

    - name: Start the application
      run: |
        pynest create-nest-app -n NestApp
        cd NestApp
        pynest generate-module -n user
        uvicorn "app:app" --host "0.0.0.0" --port "8000" --reload

    - name: Test the application
      run: |
        curl http://localhost:8000/docs
        curl get http://localhost:8000/user/
        curl post http://localhost:8000/user/ -d '{"name": "test"}'
