name: Integration Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or any version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Start the application
      run: |
        pynest create-nest-app -n NestApp -db sqlite
        cd NestApp
        pynest generate-module -n user
        python main.py &
        sleep 10  # Wait for the server to start

    - name: Test the application
      run: |
        curl http://localhost:8000/docs
        curl get http://localhost:8000/get_user
        curl post http://localhost:8000/add_user -d '{"name": "test"}'
