name: Integration Test

on: [ push, workflow_call ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or any version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Start Blank Application
        run: |
          pynest create-nest-app -n NestApp
          cd NestApp
          pynest g module -n user
          uvicorn "app:app" --host "0.0.0.0" --port "8000" --reload &

      - name: Wait for the server to start
        run: |
          sleep 10  # Wait for 10 seconds to ensure the server is up

      - name: Test the application
        run: |
          curl -f http://localhost:8000/docs
          curl -f -X 'POST' \
            'http://0.0.0.0:8000/user/' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{"name": "Example Name"}'
          curl -f http://localhost:8000/user/

      - name: Kill the server
        run: |
          kill $(jobs -p) || true


      - name: Wait fot the server to die
        run: |
          sleep 10  # Wait for 10 seconds to ensure the server is down


      - name: Start Sync ORM Application
        run: |
          pynest create-nest-app -n ORMNestApp -db sqlite
          cd ORMNestApp
          pynest g module -n user
          uvicorn "app:app" --host "0.0.0.0" --port "8080" --reload &

      - name: Wait for the server to start
        run: |
          sleep 10  # Wait for 10 seconds to ensure the server is up

      - name: Test the application
        run: |
          curl -f http://localhost:8000/docs
          curl -f -X 'POST' \
            'http://0.0.0.0:8080/user/' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{"name": "Example Name"}'
          curl -f http://localhost:8080/user/

      - name: Kill the server
        run: |
          kill $(jobs -p) || true
