name: Tests

on: [push, workflow_call]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check black formatter
      uses: psf/black@stable
      with:
        options: "--check"
        version: "23.1.0"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install python dependencies
      run: poetry install --with test

    - name: Run tests
      run: poetry run pytest tests

  integration-test:
    uses: ./.github/workflows/integration_test.yaml
